# Generated by Django 4.1.7 on 2023-05-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='tags',
            field=models.CharField(default='', max_length=200),
        ),
    ]
