# Generated by Django 4.1.7 on 2023-05-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_offer_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='company_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
