# Generated by Django 4.1.7 on 2023-05-07 12:55

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('jobs', '0003_offer_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='tags',
        ),
        migrations.AddField(
            model_name='offer',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
