name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Use Node 16
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./backend/mysite/requirements.txt
    - name: Run Tests
      run: |
        python ./backend/mysite/manage.py test
    - name: Install Railway
      run: npm i -g @railway/cli
    - name: Deploy
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY }}
